# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from promotion.grpc.v1alpha1 import promotion_api_pb2 as promotion_dot_grpc_dot_v1alpha1_dot_promotion__api__pb2


class DiscountAPIStub(object):
  """DiscountAPI export products listings endpoints.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RetrieveDiscount = channel.unary_unary(
        '/promotion.grpc.v1alpha1.DiscountAPI/RetrieveDiscount',
        request_serializer=promotion_dot_grpc_dot_v1alpha1_dot_promotion__api__pb2.RetrieveDiscountRequest.SerializeToString,
        response_deserializer=promotion_dot_grpc_dot_v1alpha1_dot_promotion__api__pb2.RetrieveDiscountResponse.FromString,
        )


class DiscountAPIServicer(object):
  """DiscountAPI export products listings endpoints.
  """

  def RetrieveDiscount(self, request, context):
    """RetrieveDiscount.
    This enables discounts by product sku
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiscountAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RetrieveDiscount': grpc.unary_unary_rpc_method_handler(
          servicer.RetrieveDiscount,
          request_deserializer=promotion_dot_grpc_dot_v1alpha1_dot_promotion__api__pb2.RetrieveDiscountRequest.FromString,
          response_serializer=promotion_dot_grpc_dot_v1alpha1_dot_promotion__api__pb2.RetrieveDiscountResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'promotion.grpc.v1alpha1.DiscountAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
