# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: promotion/grpc/v1alpha1/promotion_api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from promotion.grpc.v1alpha1 import discount_pb2 as promotion_dot_grpc_dot_v1alpha1_dot_discount__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='promotion/grpc/v1alpha1/promotion_api.proto',
  package='promotion.grpc.v1alpha1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n+promotion/grpc/v1alpha1/promotion_api.proto\x12\x17promotion.grpc.v1alpha1\x1a&promotion/grpc/v1alpha1/discount.proto\">\n\x17RetrieveDiscountRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\"P\n\x18RetrieveDiscountResponse\x12\x34\n\tdiscounts\x18\x01 \x03(\x0b\x32!.promotion.grpc.v1alpha1.Discount2\x88\x01\n\x0b\x44iscountAPI\x12y\n\x10RetrieveDiscount\x12\x30.promotion.grpc.v1alpha1.RetrieveDiscountRequest\x1a\x31.promotion.grpc.v1alpha1.RetrieveDiscountResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[promotion_dot_grpc_dot_v1alpha1_dot_discount__pb2.DESCRIPTOR,])




_RETRIEVEDISCOUNTREQUEST = _descriptor.Descriptor(
  name='RetrieveDiscountRequest',
  full_name='promotion.grpc.v1alpha1.RetrieveDiscountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='promotion.grpc.v1alpha1.RetrieveDiscountRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='promotion.grpc.v1alpha1.RetrieveDiscountRequest.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=174,
)


_RETRIEVEDISCOUNTRESPONSE = _descriptor.Descriptor(
  name='RetrieveDiscountResponse',
  full_name='promotion.grpc.v1alpha1.RetrieveDiscountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='discounts', full_name='promotion.grpc.v1alpha1.RetrieveDiscountResponse.discounts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=256,
)

_RETRIEVEDISCOUNTRESPONSE.fields_by_name['discounts'].message_type = promotion_dot_grpc_dot_v1alpha1_dot_discount__pb2._DISCOUNT
DESCRIPTOR.message_types_by_name['RetrieveDiscountRequest'] = _RETRIEVEDISCOUNTREQUEST
DESCRIPTOR.message_types_by_name['RetrieveDiscountResponse'] = _RETRIEVEDISCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RetrieveDiscountRequest = _reflection.GeneratedProtocolMessageType('RetrieveDiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVEDISCOUNTREQUEST,
  '__module__' : 'promotion.grpc.v1alpha1.promotion_api_pb2'
  # @@protoc_insertion_point(class_scope:promotion.grpc.v1alpha1.RetrieveDiscountRequest)
  })
_sym_db.RegisterMessage(RetrieveDiscountRequest)

RetrieveDiscountResponse = _reflection.GeneratedProtocolMessageType('RetrieveDiscountResponse', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVEDISCOUNTRESPONSE,
  '__module__' : 'promotion.grpc.v1alpha1.promotion_api_pb2'
  # @@protoc_insertion_point(class_scope:promotion.grpc.v1alpha1.RetrieveDiscountResponse)
  })
_sym_db.RegisterMessage(RetrieveDiscountResponse)



_DISCOUNTAPI = _descriptor.ServiceDescriptor(
  name='DiscountAPI',
  full_name='promotion.grpc.v1alpha1.DiscountAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=259,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='RetrieveDiscount',
    full_name='promotion.grpc.v1alpha1.DiscountAPI.RetrieveDiscount',
    index=0,
    containing_service=None,
    input_type=_RETRIEVEDISCOUNTREQUEST,
    output_type=_RETRIEVEDISCOUNTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOUNTAPI)

DESCRIPTOR.services_by_name['DiscountAPI'] = _DISCOUNTAPI

# @@protoc_insertion_point(module_scope)
