version: '3'
services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: swordfish
      POSTGRES_DB: promotion
    ports:
      - 5432:5432
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775
      - "6831:6831/udp"
      - "6832:6832/udp"
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
