version: 2.1

jobs:
  test:
  build:
    docker:
      - image:  circleci/python:3.8.2
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Install
          command: make install
      - run:
          name: Test Dependencies
          command: pip install .[test]
      - run:
          name: Security checker
          command: make security
      - run:
          name: Static type checker
          command: make typping
      - run:
          name: Lint code
          command: make lint
      - run:
          name: Test
          command: make test

workflows:
  main:
    jobs:
      - test
