version: 2.1

jobs:
  test:
    working_directory: ~/promotion
    docker:
      - image: circleci/python:3.8.2-buster
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: swordfish
          POSTGRES_DB: test_promotion
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install .[test,dev]
      - run:
          name: Security checker
          command: make security
      - run:
          name: Static type checker
          command: make typping
      - run:
          name: Lint code
          command: make lint
      - run:
          name: Enviroment variables
          command: cp local.env .env
      - run:
          name: Test
          command: make test

workflows:
  main:
    jobs:
      - test
