version: 2.1

jobs:
  test:
    working_directory: ~/promotion
    docker:
      - image: circleci/python:3.8.2-buster
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install .[test]
      - run:
          name: Security checker
          command: make security
      - run:
          name: Static type checker
          command: make typping
      - run:
          name: Lint code
          command: make lint
      - run:
          name: Test
          command: make test

workflows:
  main:
    jobs:
      - test
