# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from promotion.grpc.v1alpha2 import promotion_api_pb2 as promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2


class PromotionAPIStub(object):
  """PromotionAPI export promotions endpoints.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RetrievePromotion = channel.unary_unary(
        '/promotion.grpc.v1alpha2.PromotionAPI/RetrievePromotion',
        request_serializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.RetrievePromotionRequest.SerializeToString,
        response_deserializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.RetrievePromotionResponse.FromString,
        )
    self.CreateUser = channel.unary_unary(
        '/promotion.grpc.v1alpha2.PromotionAPI/CreateUser',
        request_serializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.CreateUserResponse.FromString,
        )


class PromotionAPIServicer(object):
  """PromotionAPI export promotions endpoints.
  """

  def RetrievePromotion(self, request, context):
    """RetrievePromotion.
    This retrieve all discounts by product and user IDs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateUser(self, request, context):
    """CreateUser
    This is used to populate user data store.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PromotionAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RetrievePromotion': grpc.unary_unary_rpc_method_handler(
          servicer.RetrievePromotion,
          request_deserializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.RetrievePromotionRequest.FromString,
          response_serializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.RetrievePromotionResponse.SerializeToString,
      ),
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.CreateUserRequest.FromString,
          response_serializer=promotion_dot_grpc_dot_v1alpha2_dot_promotion__api__pb2.CreateUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'promotion.grpc.v1alpha2.PromotionAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
